### ISSUE TITLE
Review ALZ assignments and add comments to parameters

### ISSUE THREAD

**Issue by anwather** [Azure/enterprise-azure-policy-as-code#381]
```[tasklist]
### Tasks
- [x] Add comments to parameters
- [x] Update file names to ALZ
- [x] Add documentation to rename files
- [x] Add platform assignment
```
